### ISSUE TITLE
In App When i tried to pick an image im getting error

### ISSUE THREAD

**Issue by ghost** [jashasweejena/Ml-Kit-face-detection#1]
I am getting image picker error

**Comment by jashasweejena** [comment]
Can you please show me the exact error in logcat?

**Comment by jashasweejena** [comment]
You have turned off sharing access in this drive link. Please enable it.

**Comment by DroidDetector** [comment]
[FaceDetection.zip](https://github.com/jashasweejena/Ml-Kit-face-detection/files/2031007/FaceDetection.zip)

My files

**Comment by DroidDetector** [comment]
Still giving "Image picker error"
